Repository swift-wallet/sdp2022, pull requests merged in 2022-03, with the labels that each got.

#8 Ajout bail
  README.md
Labels: enhancement

#32 Fix cirrus
  .cirrus.yml
Labels: bug

#35 Add QR Code Scanning and Generation Feature
  app/build.gradle
  app/src/androidTest/java/com/sdp/swiftwallet/QRActivityTest.java
  app/src/androidTest/java/com/sdp/swiftwallet/QRCodeGeneratorTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sdp/swiftwallet/QRActivity.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/Login.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/QRCode.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/QRCodeGenerator.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/QRCodeScanner.java
  app/src/main/res/layout/activity_qractivity.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#60 New MainActivity as app Hub
  app/build.gradle
  app/src/androidTest/java/com/sdp/swiftwallet/LoginActivityTest.java
  app/src/androidTest/java/com/sdp/swiftwallet/MainActivityTest.java
  app/src/androidTest/java/com/sdp/swiftwallet/SignInTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sdp/swiftwallet/GreetingActivity.java
  app/src/main/java/com/sdp/swiftwallet/LoginActivity.java
  app/src/main/java/com/sdp/swiftwallet/MainActivity.java
  app/src/main/java/com/sdp/swiftwallet/ProfileActivity.java
  app/src/main/java/com/sdp/swiftwallet/domain/use_case/Filler.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/HomeFragment.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/MessageFragment.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/PaymentFragment.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/ProfileFragment.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/StatsFragment.java
  app/src/main/res/drawable-anydpi/ic_home.xml
  app/src/main/res/drawable-anydpi/ic_message.xml
  app/src/main/res/drawable-anydpi/ic_payment.xml
  app/src/main/res/drawable-anydpi/ic_profile.xml
  app/src/main/res/drawable-anydpi/ic_stats.xml
  app/src/main/res/drawable-hdpi/ic_home.png
  app/src/main/res/drawable-hdpi/ic_message.png
  app/src/main/res/drawable-hdpi/ic_payment.png
  app/src/main/res/drawable-hdpi/ic_profile.png
  app/src/main/res/drawable-hdpi/ic_stats.png
  app/src/main/res/drawable-mdpi/ic_home.png
  app/src/main/res/drawable-mdpi/ic_message.png
  app/src/main/res/drawable-mdpi/ic_payment.png
  app/src/main/res/drawable-mdpi/ic_profile.png
  app/src/main/res/drawable-mdpi/ic_stats.png
  app/src/main/res/drawable-xhdpi/ic_home.png
  app/src/main/res/drawable-xhdpi/ic_message.png
  app/src/main/res/drawable-xhdpi/ic_payment.png
  app/src/main/res/drawable-xhdpi/ic_profile.png
  app/src/main/res/drawable-xhdpi/ic_stats.png
  app/src/main/res/drawable-xxhdpi/ic_home.png
  app/src/main/res/drawable-xxhdpi/ic_message.png
  app/src/main/res/drawable-xxhdpi/ic_payment.png
  app/src/main/res/drawable-xxhdpi/ic_profile.png
  app/src/main/res/drawable-xxhdpi/ic_stats.png
  app/src/main/res/layout/activity_greeting.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_payment.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_stats.xml
  app/src/main/res/menu/bottom_bar.xml
  app/src/main/res/values/strings.xml
Labels: major

#75 Address creation system
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sdp/swiftwallet/TransactionHistoryActivity.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/wallet/IWalletKeyPair.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/wallet/IWallets.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/wallet/WalletKeyPair.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/wallet/Wallets.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/wallet/cryptography/KeyPairGenerator.java
  app/src/main/java/com/sdp/swiftwallet/domain/model/wallet/cryptography/SeedGenerator.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/HomeFragment.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/StatsFragment.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/wallets/WalletItem.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/wallets/WalletItemFragment.java
  app/src/main/java/com/sdp/swiftwallet/presentation/fragments/wallets/WalletItemRecyclerViewAdapter.java
  app/src/main/res/drawable/ether.png
  app/src/main/res/drawable/fragment_seed.xml
  app/src/main/res/drawable/ic_baseline_add_circle_outline_24.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_payment.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_stats.xml
  app/src/main/res/layout/fragment_wallet_item.xml
  app/src/main/res/layout/fragment_wallet_item_list.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  local.properties
Labels: enhancement

#80 Remove local.props and add .gitignore
  .gitignore
  local.properties
Labels: bug
